// <auto-generated />
namespace SimpleBankATM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedidentityauthbutturneditoff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedidentityauthbutturneditoff));
        
        string IMigrationMetadata.Id
        {
            get { return "201610230903168_added identity auth, but turned it off"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
